- name: Install EPEL repo.
  yum:
    name: "epel-release"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install Xvfb
  yum: name=xorg-x11-server-Xvfb state=present

- name: Add Xvfb service
  template:
    src=xvfb.j2
    dest=/etc/init.d/xvfb
    mode="u=rwx,g=rx,o=rx"

- name: Add Xvfb to startup
  command: "chkconfig xvfb on"

- name: Start Xvfb
  command: "service xvfb start"

- name: check if Firefox is already downloaded
  stat: path={{firefox_rpm_location}}
  register: downloaded_firefox

- set_fact:
    force_new_firefox_download: "{{ downloaded_firefox.stat.md5 != md5_checksum_of_firefox }}"
  when: downloaded_firefox.stat.exists

- name: Delete firefox rpm if checksum does not match
  file: path={{ firefox_rpm_location }} state=absent
  when: "{{ force_new_firefox_download == true }}"

- name: Download Firefox
  get_url:
    url: "{{firefox_download_url}}"
    dest: "{{download_folder}}"
  when: "{{ downloaded_firefox.stat.exists == false  }} or {{ force_new_firefox_download == true }}"

- name: Install Firefox
  yum:
    name: "{{firefox_rpm_location}}"
    state: present
