---
- ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
      instance-state-name: running
      'tag:type': "{{ config.proxy_type }}"
  register: proxy_instances

- name: Add proxy to dynamic host group
  add_host:
    name: "{{ item.tags.Name }}"
    groupname: gatewayed
    ansible_ssh_host: "{{ item.private_ip_address }}"
    ansible_user: centos
  with_items: "{{ proxy_instances.instances }}"

- name: install haproxy
  delegate_to: "{{ item.tags.Name }}"
  become: yes
  yum: name=haproxy state=present
  with_items: "{{ proxy_instances.instances }}"

- name: start haproxy
  delegate_to: "{{ item.tags.Name }}"
  become: yes
  service: name=haproxy state=started
  with_items: "{{ proxy_instances.instances }}"

- ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
       instance-state-name: running
       'tag:server_type': "{{config.target_server_type}}"
  register: target_proxy_instances

- name: Copy haproxy config
  delegate_to: "{{ item.tags.Name }}"
  become: yes
  template:
      src=haproxy.cfg.j2
      dest=/etc/haproxy/haproxy.cfg
      backup=yes
      mode=755
  with_items: "{{ proxy_instances.instances }}"

- ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
       instance-state-name: running
       'tag:role': 'build-server'
  register: bahmni_server_instances

- name: Add go server
  become: yes
  replace:
    dest: /etc/haproxy/haproxy.cfg
    regexp: '^backend ci[\s\S]* server ci \d+\.\d+\.\d+\.\d+\:\d+\s*$'
    replace: "backend ci \n redirect scheme https if !{ ssl_fc } \n mode http \n server ci {{bahmni_server_instances.instances[0].private_ip_address}}:8153\n"
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ proxy_instances.instances }}"

- name: Restart haproxy
  delegate_to: "{{ item.tags.Name }}"
  become: yes
  service: name=haproxy state=reloaded
  with_items: "{{ proxy_instances.instances }}"
