---
- name: Set hostname for aws host
  hostname: name="{{ ec2_tag_Name }}"
  become: yes

- name: Update hostname to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='127.0.0.1 localhost localhost.localdomain {{ ec2_tag_Name }}'
    regexp='^127\.0\.0\.1'
    insertafter='^127\.0\.0\.1'
    state=present