- hosts: all
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
   - hostname
  vars_files:
   - "group_vars/users.yml"