- hosts: '{{ host }}'
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
    - epel-repo
    - oracle-java
    - build-utils
    - ruby2.2.2
    - go-agent
    - postgres
    - mysql
    - maven
    - firefox
    - chrome
    - gauge
  vars_files:
    - "group_vars/vars.yml"
  tags:
    - provision_build_agent

- hosts: tag_role_bastion-server
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
   - bastion
  vars_files:
   - "group_vars/vars.yml"
  tags:
    - provision_bastion

- hosts: tag_Name_ci
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
   - mysql
   - epel-repo
   - buildserver
  vars_files:
   - "group_vars/vars.yml"
  tags:
    - provision_build_server

- hosts: tag_role_proxy_server
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
    - haproxy
  vars_files:
    - "group_vars/aws_credentials.yml"
  tags:
    - update_proxy

- hosts: tag_role_bahmni_server
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
    - ssl-certs
  vars_files:
    - "group_vars/aws_credentials.yml"
    - "group_vars/cidr_blocks.yml"
  tags:
    - renew_certs

- hosts: tag_role_bahmni_server
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
   - epel-repo
   - oracle-java
   - go-agent
  vars_files:
    - "group_vars/vars.yml"
  tags:
    - provision_bahmni_server