---

- hosts: all
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
    ansible_user: centos
  roles:
    - ssh-key
  vars_files:
    - "group_vars/vars.yml"
