- hosts: '{{ host }}'
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@bastion.mybahmni.org"'
   ansible_user: centos
  roles:
   - spacewalk-client
  vars_files:
   - "group_vars/users.yml"
   - "group_vars/vars.yml"