- name: Stop the instances
  ec2:
   region: "{{aws_region}}"
   aws_access_key:   "{{ aws_access_key }}"
   aws_secret_key:   "{{ aws_secret_key }}"
   instance_tags: '{"Name": "{{item.hostname | replace (".mybahmni.local", "") }}"}'
   state: stopped
   wait: True
  with_items: "{{ec2_instances}}"
  when: instance_name == 'all' and item.autostop|default("") != 'disabled'

- name: "Stop the instances {{instance_name}}"
  ec2:
   region: "{{aws_region}}"
   aws_access_key:   "{{ aws_access_key }}"
   aws_secret_key:   "{{ aws_secret_key }}"
   instance_tags: '{"Name": "{{instance_name | replace (".mybahmni.local", "") }}"}'
   state: stopped
   wait: True
  when: instance_name != 'all'