---

- include: launch_bastion.yml
- include: launch_proxy.yml
- include: launch_qa_env.yml
- include: launch_showcase_env.yml
- include: launch_assets_env.yml
- include: launch_build_agent.yml
- include: launch_build_server.yml
- include: setup_route53.yml

