- name: Start the instances {{instance_name}}
  ec2:
   region: "{{aws_region}}"
   aws_access_key:   "{{ aws_access_key }}"
   aws_secret_key:   "{{ aws_secret_key }}"
   instance_tags: '{"Name": "{{instance_name | replace (".mybahmni.local", "") }}"}'
   state: running
   wait: True
