- ec2_remote_facts:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region:           "{{ aws_region }}"
    filters:
       instance-state-name: running
       'tag:role': 'build-server'
  register: bahmni_server_instances

- name: Add servers to dynamic host group
  add_host:
    name: "{{ item.tags.Name }}"
    groupname: gatewayed
    ansible_ssh_host: "{{ item.private_ip_address }}"
    ansible_user: centos
  with_items: "{{ bahmni_server_instances.instances }}"

- name: Copy buildserver repository
  become: yes
  template: src=gocd.repo.j2 dest=/etc/yum.repos.d/gocd.repo owner=root group=root mode=0644
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"

- name: Installing Java
  become: yes
  yum: pkg=java-1.7.0-openjdk state=installed
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"

- name: Installing GoServer
  become: yes
  yum: pkg="go-server-{{goserver_installer_version}}" state=installed
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"

- name: Start goserver service
  service: name=go-server state=started
  become: yes
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"

- name: Allow GoServer access from vpc subnet
  become: yes
  lineinfile: dest=/etc/sysconfig/iptables
              state=present
              regexp="^-A INPUT -s "{{infra_cidr_blocks.vpc_cidr_block}}" -p tcp -m tcp --dport 8153 -m comment --comment "Go_Server" -j ACCEPT"
              line="-A INPUT -s "{{infra_cidr_blocks.vpc_cidr_block}}" -p tcp -m tcp --dport 8153 -m comment --comment "Go_Server" -j ACCEPT"
              insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
              backup=yes
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"

- name: restart iptables
  become: yes
  service: name=iptables state=restarted
  delegate_to: "{{ item.tags.Name }}"
  with_items: "{{ bahmni_server_instances.instances }}"






