- name: Get iptable rules
  shell: /sbin/iptables -L
  register: iptablesrules

- name: Allow GoServer port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8153 -j ACCEPT -m comment --comment "GoServer"
  when: iptablesrules.stdout.find("GoServer") == -1

- name: Allow GoServer SSl port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8154 -j ACCEPT -m comment --comment "GoServerssl"
  when: iptablesrules.stdout.find("GoServerssl") == -1

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables

- name: Copy buildserver repository
  template: src=gocd.repo.j2 dest=/etc/yum.repos.d/gocd.repo owner=root group=root mode=0644

- name: Installing Java
  yum: pkg=java-1.7.0-openjdk state=installed

- name: Installing GoServer
  yum: pkg="go-server-{{goserver_installer_version}}" state=installed

- name: Copy goserver admin credentials
  template: src=passwd_file.j2 dest=/var/lib/go-server/passwd-file owner=root group=root mode=0644

- name: Download github_oauth
  get_url:
    url: https://github.com/gocd-contrib/gocd-oauth-login/releases/download/v2.1/github-oauth-login-2.1.jar
    dest: /var/lib/go-server/plugins/external/github-oauth-login-2.1.jar
    owner: go
    group: go
    mode: 0644

- name: Download go_maven_poller
  get_url:
    url: https://github.com/1and1/go-maven-poller/releases/download/v1.1.4/go-maven-poller.jar
    dest: /var/lib/go-server/plugins/external/go-maven-poller.jar
    owner: go
    group: go
    mode: 0644

- name: Download go_slack_notifier
  get_url:
    url: https://github.com/ashwanthkumar/gocd-slack-build-notifier/releases/download/v1.3.1/gocd-slack-notifier-1.3.1.jar
    dest: /var/lib/go-server/plugins/external/gocd-slack-notifier-1.3.1.jar
    owner: go
    group: go
    mode: 0644

- name: Start goserver service
  service: name=go-server state=started