bastion_spec:
   Tags: {"role": "bastion-server"}
   StartIndex: 1
   ExactCount: 1
   InstanceType: t2.micro
   public_ip: "52.220.233.188"
   SecurityGroups:
     - "{{ SecurityGroupIds.bastion }}"
   AmiId: "{{ available_amis.hardened_ami }}"
   SubnetId: "{{ SubnetIds.public }}"
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 40
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: yes
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /
