build_agent_spec:
   Tags: {"role": "build-agent"}
   StartIndex: 1
   ExactCount: 1
   InstanceType: m4.large
   SecurityGroups:
     - "{{ SecurityGroupIds.bahmni }}"
   AmiId: "{{ available_amis.bahmni_ami }}"
   SubnetId: "{{ SubnetIds.build }}"
   AssignPublicIp: no
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 40
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: yes
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /