ec2_instances:
  - { hostname: bastion, spec: "{{ bastion_spec }}", autoStop: disabled}
  - { hostname: tw_proxy, spec: "{{ tw_proxy_spec }}", autoStop: disabled}
  - { hostname: public_proxy, spec: "{{ public_proxy_spec}}", autoStop: disabled }
  - { hostname: ci, spec: "{{ build_server_spec }}", autoStop: disabled}
  - { hostname: ci-agent01, spec: "{{ build_agent_spec }}" }
  - { hostname: ci-agent02, spec: "{{ build_agent_spec }}" }
  - { hostname: ci-agent03, spec: "{{ build_agent_spec }}" }
  - { hostname: product-qa02, spec: "{{ qa_env_spec }}", autoStart: disabled }
  - { hostname: product-qa03, spec: "{{ qa_env_spec }}" }
  - { hostname: product-qa04, spec: "{{ qa_env_spec }}" }
  - { hostname: product-qa08, spec: "{{ qa_env_spec }}", autoStart: disabled }
  - { hostname: product-qa09, spec: "{{ qa_env_spec }}" }
  - { hostname: product-perf, spec: "{{ qa_env_spec }}" }
  - { hostname: connect-emu01, spec: "{{ connect_genymotion_spec }}" }
  - { hostname: product-ftagent02, spec: "{{ qa_env_spec }}" }
  - { hostname: product-ftagent03, spec: "{{ qa_env_spec }}" }
  - { hostname: controller, spec: "{{ assets_env_spec }}", autoStop: disabled }
  - { hostname: banyan01, spec: "{{ showcase_env_spec }}" }
  - { hostname: jss-showcase01, spec: "{{ showcase_env_spec }}" }

startInstance: {minute: 30, hour: 05, weekday: "1-5" }
stopInstance: {minute: 00, hour: 20, weekday: "1-5" }
