ec2_instances:
  - { hostname: docker-agent01, spec: "{{ docker_host_env_spec }}" }
  - { hostname: bastion, spec: "{{ bastion_spec }}", autostop: disabled}
  - { hostname: tw_proxy, spec: "{{ tw_proxy_spec }}", autostop: disabled}
  - { hostname: public_proxy, spec: "{{ public_proxy_spec}}", autostop: disabled }
  - { hostname: ci, spec: "{{ build_server_spec }}", autostop: disabled}
  - { hostname: ci-agent01, spec: "{{ build_agent_spec }}" }
  - { hostname: ci-agent02, spec: "{{ build_agent_spec }}" }
  - { hostname: ci-agent03, spec: "{{ build_agent_spec }}" }
  - { hostname: product-qa02, spec: "{{ qa_env_spec }}", autostart: disabled }
  - { hostname: connect-emu01, spec: "{{ connect_genymotion_spec }}", autostart: disabled }
  - { hostname: controller, spec: "{{ assets_env_spec }}", autostop: disabled }
  - { hostname: banyan01, spec: "{{ showcase_env_spec }}" }
  - { hostname: jss-showcase01, spec: "{{ showcase_env_spec }}" }
