tw_proxy_spec:
   Tags: {"role": "proxy-server", "type": "private"}
   StartIndex: 1
   ExactCount: 1
   InstanceType: t2.micro
   SecurityGroups:
     - "{{ SecurityGroupIds.tw_proxy }}"
   AmiId: "{{ available_amis.hardened_ami }}"
   SubnetId: "{{ SubnetIds.public }}"
   public_ip: "52.220.231.34"
   InstanceVolumes:
     - VolumeSpecifications:
         - volume_size: 40
           volume_type: gp2
           device_name: /dev/sda1
           delete_on_termination: yes
           FilesystemSpecifications:
             volume_label: "root"
           mountpoint: /