- name: Install Apache server from yum repository
  yum: name={{item}} state=present
  with_items:
   - httpd
   - mod_ssl
   - mod_wsgi

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep "WEB SERVER"  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 80 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  80 -j ACCEPT -m comment --comment "WEB SERVER"

- name: save iptables
  command: service iptables save

- name: Get matched IpTable rule
  shell: iptables -nL --line-numbers | grep https  -m 1 | cut -c 1-2
  register: matchedRule

- name: delete matching rule if exists
  shell: iptables -D INPUT {{ matchedRule.stdout }}
  when: matchedRule.stdout!=""

- name: Allow port 443 through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport  443 -j ACCEPT -m comment --comment "https"

- name: save iptables
  command: service iptables save

- name: create bahmni-certs directory
  file: path=/etc/bahmni-certs state=directory owner={{ certs_user }} group={{ certs_group }} mode=755

- name: check if certificate already points to letsencrypt
  stat: path=/etc/bahmni-certs/cert.crt
  register: certificate_link

- name: link local certificate and domain key
  file: src={{ item.src }}  dest={{ item.dest }} state=link
  with_items:
    - { src: /etc/pki/tls/certs/localhost.crt, dest: /etc/bahmni-certs/cert.crt}
    - { src: /etc/pki/tls/certs/localhost.crt, dest: /etc/bahmni-certs/chained.pem}
    - { src: /etc/pki/tls/private/localhost.key, dest: /etc/bahmni-certs/domain.key}
  when: certificate_link.stat.exists == False

- name: Start httpd
  service: name=httpd state=started enabled=yes

- name: remove ssl.conf
  file: path=/etc/httpd/conf.d/ssl.conf state=absent

- name: set policy for SeLinux
  seboolean: name={{ item }} state=yes persistent=yes
  with_items:
    - httpd_enable_cgi
    - httpd_can_network_connect


