- hosts: localhost
  vars_files:
     - "../../group_vars/aws_credentials.yml"
  tasks:
  - name: terminate deployment instances
    include: ../terminate_instance.yml
    vars:
      - instance_name: "{{ deploy_instances[0] }}"
