---
- name: Install supporting utils
  yum: name={{item}} state=present
  with_items:
     - git
     - ansible
     - python-crypto
     - python-paramiko
     - python-keyczar

- name: Add gocd yum repo
  become: yes
  template:
    src=gocd.repo.j2
    dest=/etc/yum.repos.d/gocd.repo owner=root group=root mode=0644

- name: Install go-agent
  yum: name="{{ java_installer_version }}" state=present

- name: Install go-agent
  yum: name="go-agent-{{ go_agent_version }}" state=present

- name: Set GO_SERVER as ci.mybahmni.org
  template:
    src=go-agent.j2
    dest=/etc/default/go-agent
  notify: Start go-agent

- name: Create Folder to copy the pem file
  file: path=/var/go/.keys/ owner=go group=go mode=0755 state=directory

- name: Drop in Ansible vault pem file
  template:
    src=secret.pem.j2
    dest=/var/go/.keys/secret.pem owner=go group=go mode=0644

- name: Remove require tty
  lineinfile: regexp="^Defaults\s+requiretty" dest=/etc/sudoers state=absent

- name: Add user go to sudoers group
  lineinfile: dest=/etc/sudoers state=present regexp='^go ALL\=' line='go ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'
