---
- name: Setup VPC
  pause: prompt='Run for new VPC setup / Update new changes in VPC .! Press Ctrl+c and then "a" to abort'

- include: vpc.yml
- include: subnet.yml
- include: igw.yml
- include: nat.yml
- include: route_table.yml
- include: security_group.yml

